### ISSUE TITLE
Many messages are lost if there are concurrent clients sending them

### ISSUE THREAD

**Issue by tomzx** [hoaproject/Websocket#58] opened 2015-11-26 02:40 UTC
Hello,

I've been playing with many concurrent clients calling a server so that it rebroadcasts the sent message to other clients. However, the sad news is that it appears I'm losing almost 20%-30% of those messages when I have 5 or more concurrent connections.

A simple test case is as follow:

**server.php**

```
$i = 0;
$j = 0;
$k = 0;

$websocket = new Hoa\Websocket\Server(
    new Hoa\Socket\Server('tcp://127.0.0.1:8889')
);
$websocket->on('open', function (Hoa\Core\Event\Bucket $bucket) use (&$i) {
    echo 'connection ' . ++$i . PHP_EOL;
});
$websocket->on('message', function (Hoa\Core\Event\Bucket $bucket) use (&$j) {
    echo 'message ' .++$j.PHP_EOL;
});
$websocket->on('close', function (Hoa\Core\Event\Bucket $bucket) use (&$k) {
    echo 'connection closed ' . ++$k . PHP_EOL;
});
$websocket->run();
```

**client.php**

```
$client   = new Hoa\Websocket\Client(
    new Hoa\Socket\Client('tcp://127.0.0.1:8889')
);
$client->setHost('test');
$client->connect();

$client->send('HELLO WORLD');
```

**test command**

```
ab -n 500 -c 5 -B 127.0.0.1 http://localhost/client.php
```

Here's what I see at the end of a run:

```
connection 500
message 372
connection closed 369
```

What I'd expect:

```
connection 500
message 500
connection closed 500
```

I haven't investigated yet as to what the issue is, but considering that all connection are properly made, something occurs between the time the connection is made and the time a message is supposed to be sent. It is also interesting to note that many connections aren't closed as well, which doesn't sound good.

Tested different concurrency levels:

| Concurrency | messages retransmitted/connections | messages delivered overall |
| --- | --- | --- |
| 1 | 500/500 | 100% |
| 2 | 464/500 | 93% |
| 3 | 433/500 | 87% |
| 4 | 398/500 | 80% |
| 5 | 362/500 | 72% |
| 500 | 250/500 | 50% |

**Edit 1:** After some more testing and playing around, it seems very critical for the client code to call `$client->close();`. Doing so increases the rate of message delivered to almost 100% (but not 100%).

Suggested: Implement the `__destruct` method in `Client`s classes so that they may close their connection cleanly (if the user didn't call `close()` himself).

Furthermore, it appears that the connections that do not end up triggering a `close` event are actually triggering an `error` event. It has to do with the fact that we try to write to a socket that has been closed.

**Comment by Hywan** [comment] 2015-11-26 08:29
Hello!

Thank you for the very detailled report! We are going to investigate.

**Comment by Hywan** [comment] 2015-11-26 08:39
@tomzx On what platform are you testing? Moreover, what is the VM you're using (with the version please)? Because, I tried and here are my results:

| Concurrency | messages retransmitted/connections | messages delivered overall |
|---|---|---|
| 1 | 500/500 | 100% |
|2| 500/500 | 100% |
|3| 500/500 | 100% |
|4| 500/500| 100% |
|5| 500/500 | 100% |
|100| 500/500 | 100% |
|500| HTTP server fail | N/A |

Note: I have PHP7-nightly and I am using build-in HTTP server.

**Comment by Hywan** [comment] 2015-11-26 08:40
This is not because I can't reproduce that your ideas are bad. They are smart and we are going to implement them I guess.

**Comment by Metalaka** [comment] 2015-11-26 12:29
500/500/500 on Win x64, php 5.5, apache 2.4.9, websocket@2.15.08.05.

**Comment by tomzx** [comment] 2015-11-26 14:08
@Hywan I've tested on Windows 7 x64, php 5.6.4, apache 2.4.7. I used `ab` from cygwin.

@Hywan, @Metalaka What platform did you use? Where was `ab` run from?

Furthermore, how are you getting those 100% results? Have you patched the code with any fixes or it is working flawlessly for both of you? I'm asking, considering the 2 PR/fixes that are currently being investigated should generally trigger within a run with concurrency and thus crash the server.

I've discovered my initial issues (`_send` crashing) at work on a Mac OS X Yosemite computer, however I'm unsure if that computer had any message delivery issues... I'll give that a try this morning when I get there.

**Comment by Metalaka** [comment] 2015-11-26 20:13
For my result, I simply`composer require hoa/websocket` (currently: 2.15.08.05) and copy past your code (so doesn't include your 2 PR).

The test isn't related to https://github.com/hoaproject/Websocket/pull/57 since here we don't broadcast any messages.

**Comment by Hywan** [comment] 2015-11-27 08:36
@tomzx Exactly like @Metalaka. I have been testing on Mac OS X (Yosemite). Did you try with your 2 PR checked out?

**Comment by tomzx** [comment] 2015-11-27 14:39
@Hywan I did as the server would crash pretty much right away otherwise.

**Comment by Hywan** [comment] 2015-11-27 14:52
@tomzx Hmmm… This is very strange. So you have the same configuration than @Metalaka. You didn't try with `hoa/websocket@latest` because it crashes immediately. You did try with your 2 PR applied. Maybe @camael24 can reproduce. Help?

**Comment by camael24** [comment] 2015-11-28 13:00
Hi i test on my computer windows 10 64bits with php 5.6.15 apache and ab

I have this result : 
```
$ ab -n 500 -c 5 -B 127.0.0.1 http://localhost/client.php
This is ApacheBench, Version 2.3 <$Revision: 1663405 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking localhost (be patient)
Completed 100 requests
Completed 200 requests
Completed 300 requests
Completed 400 requests
Completed 500 requests
Finished 500 requests


Server Software:        Apache/2.4.16
Server Hostname:        localhost
Server Port:            80

Document Path:          /client.php
Document Length:        0 bytes

Concurrency Level:      5
Time taken for tests:   12.243 seconds
Complete requests:      500
Failed requests:        0
Total transferred:      100500 bytes
HTML transferred:       0 bytes
Requests per second:    40.84 [#/sec] (mean)
Time per request:       122.434 [ms] (mean)
Time per request:       24.487 [ms] (mean, across all concurrent requests)
Transfer rate:          8.02 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:        0    0   0.5      0      10
Processing:    55  121 473.4     87   10490
Waiting:       55  121 473.4     87   10490
Total:         56  122 473.4     87   10491

Percentage of the requests served within a certain time (ms)
  50%     87
  66%    101
  75%    114
  80%    122
  90%    157
  95%    182
  98%    235
  99%    289
 100%  10491 (longest request)
```

and : 
```
php server.php
connection 500
message 500
connection closed 500
```
      "hoa/websocket": "^2.15"

Cheers

**Comment by tomzx** [comment] 2015-11-29 04:59
Alright guys, I made a mistake in my initial post. This should be the server.php code you should test with:

````
$i = 0;
$j = 0;
$k = 0;

$websocket = new Hoa\Websocket\Server(
    new Hoa\Socket\Server('tcp://127.0.0.1:8889')
);
$websocket->on('open', function (Hoa\Core\Event\Bucket $bucket) use (&$i) {
    echo 'connection ' . ++$i . PHP_EOL;
});
$websocket->on('message', function (Hoa\Core\Event\Bucket $bucket) use (&$j) {
    echo 'message ' .++$j.PHP_EOL;
    $data = $bucket->getData();
    $bucket->getSource()->broadcast($data['message']);
});
$websocket->on('close', function (Hoa\Core\Event\Bucket $bucket) use (&$k) {
    echo 'connection closed ' . ++$k . PHP_EOL;
});
$websocket->run();
```

Notice that it gets the data and then rebroadcasts it. This is the part that was missing from my original example.

**Comment by Hywan** [comment] 2015-11-30 07:01
@camael24 Thanks for your time and your feedback!

**Comment by Hywan** [comment] 2015-11-30 07:05
@tomzx Sorry…

| Concurrency | messages retransmitted/connections | messages delivered overall |
|---|---|---|
| 1 | 500/500 | 100% |
|2| 500/500 | 100% |
|3| 500/500 | 100% |
|4| 500/500| 100% |
|5| 500/500 | 100% |
|100| 500/500 | 100% |
|500| HTTP server fail | N/A |

**Comment by Metalaka** [comment] 2015-11-30 08:06
@Hywan with this `server.php` and both PR I've similar results that @tomzx

**Comment by Hywan** [comment] 2015-11-30 08:07
@Metalaka What about with no PR?

**Comment by Metalaka** [comment] 2015-11-30 08:08
@Hywan the error described in https://github.com/hoaproject/Websocket/pull/57

**Comment by Hywan** [comment] 2015-11-30 12:02
@Metalaka If you can reproduce, that's great. Please, try to find in which order we have to fix these issues.

**Comment by Hywan** [comment] 2015-11-30 12:02
@Metalaka And ask help if needed!

**Comment by Metalaka** [comment] 2015-11-30 12:28
@Hywan I'll try this week(-end)
@tomzx do you have similar results with OSX ?

**Comment by tomzx** [comment] 2015-12-01 00:36
@Metalaka Yes, similar results on Mac OS X, PHP 5.6.16 and Apache 2.2.22.

**Comment by Hywan** [comment] 2015-12-01 07:57
This is possible I can't reproduce because of build-in HTTP server of 
PHP. I reckon it is not really asynchronous.

**Comment by tomzx** [comment] 2015-12-01 12:21
@Hywan Indeed, php built-in server is single threaded afaik.

**Comment by Hywan** [comment] 2015-12-01 12:25
@tomzx Sorry for the noise then :-(.

**Comment by camael24** [comment] 2015-12-03 10:16
I will test it this week end :/ sorry no time before :/

**Comment by Hywan** [comment] 2016-01-11 12:59
What the status of this issue?

**Comment by Hywan** [comment] 2016-02-15 07:45
@Metalaka Any news?

**Comment by Metalaka** [comment] 2016-02-15 20:39
@Hywan I'll take a look this week but like the last time I had tried it will be hard to find the issue source. Since the issue only occur in high speed/concurrent contexte, debug that isn't an easy task…

**Comment by Hywan** [comment] 2016-02-16 08:14
@Metalaka Do you think it is related to #57?

**Comment by Metalaka** [comment] 2016-02-16 19:11
@Hywan This issue seem related to the server broadcasting mechanism(since whitout broadcast, all messages are received), so because https://github.com/hoaproject/Websocket/pull/57 is about broadcasting message on a non ready node, it may be related.

**Comment by Hywan** [comment] 2016-02-24 06:57
@tomzx Can you retry with `hoa/websocket@dev` and `hoa/socket@dev` please? I hope everything should be fixed now thanks to the hard work of @Metalaka!

**Comment by tomzx** [comment] 2016-02-24 10:35
The good news is that the server doesn't appear to crash anymore.
The bad news is that I'm still seeing messages being dropped.

Updated server test code:
```php
$i = 0;
$j = 0;
$k = 0;
$l = 0;

$websocket = new Hoa\Websocket\Server(
    new Hoa\Socket\Server('tcp://127.0.0.1:8889')
);
$websocket->on('open', function (Hoa\Event\Bucket $bucket) use (&$i) {
    echo 'connection ' . ++$i . PHP_EOL;
});
$websocket->on('message', function (Hoa\Event\Bucket $bucket) use (&$j) {
    echo 'message ' .++$j.PHP_EOL;
    $data = $bucket->getData();
    $bucket->getSource()->broadcast($data['message']);
});
$websocket->on('close', function (Hoa\Event\Bucket $bucket) use (&$k) {
    echo 'connection closed ' . ++$k . PHP_EOL;
});
$websocket->on('error', function (Hoa\Event\Bucket $bucket) use (&$l) {
    echo 'error ' . ++$l . PHP_EOL;
});
$websocket->run();
```

**connection 500**
connection closed 311
**error 188**
**message 312**
**connection closed 312**

As one can see, there are `#error (188)` + `#connection closed (312)` = `#connection (500)`.

If I add `$client->close();` to the client code as suggested in the initial post, I'm getting strange results:

**connection 500**
message 490
**connection closed 193**
**message 491**
**error 330**

In this case, I'm getting a particularly low amount of connection closed (~200) and a particularly high amount of errors (~300).

Obviously this whole scenario is quite complicated by the fact that you have clients that are connecting to the server, sending their payload and then leaving as soon as possible, which means the server is attempting to broadcast to these dying connections...

**Comment by Hywan** [comment] 2016-02-24 11:22
You're right when you're saying that this is a very tricky scenario because your clients connect, send a message (that is broadcasted) and then disconnect without waiting an answer. So the server is most of the time dealing with disconnected client while broadcasting the messages.

**No longer having errors is a nice news**! The socket and websocket connections are most robust. Great. It's strange that there is not 500 closed connections. If 500 clients connect, we must have 500 clients disconnect, except… (I am thinking too fast) that we must consider errors. Sending a message to a client that is disconnecting will fire an error, so 312 closes + 188 errors = 500 “closes”. Everything seems OK in this particular scenario.

However, not all messages have been received by the server. We might expect the server to receive 500 messages since 500 clients connect and send a message. Thoughts?

**Comment by Metalaka** [comment] 2016-03-22 21:24
When there is an error while processing a node we try/force to close the current connection and then send a error event but we never send close event. The delta between open & close come from here.

https://github.com/hoaproject/Websocket/blob/ad7b3902528a2c1fe79154169c5037abd4311bec/Connection.php#L468

_____
I must always find why every messages isn't handled/counted.

**Comment by Hywan** [comment] 2016-03-23 05:46
Good luck!

Any volunteer to help @hoaproject/hoackers?

**Comment by EtienneWan** [comment] 2016-05-24 08:07
This issue looks a bit like the one I opened nearly a year ago
https://github.com/hoaproject/Websocket/issues/46 (Also on my issue, @Hywan couldn't reproduce)

Until today, I haven't tried again my test case. But if it can help for this issue, I will.
(Quick explaination: I (one client) was trying to send heavy messages to the Hoa Server I set up, and each time I was ending up with message partially read and connection closed)

**Comment by Hywan** [comment] 2016-05-24 08:13
As far as I remember, this is not the same issue because there was no concurrency, isn't it?

**Comment by EtienneWan** [comment] 2016-05-24 14:50
Yes, this is not the same issue: there was no concurrency.
But there were the same symptoms: message partially received by both the server and the client, followed by a connection close.

I only used the Server part, the client was written in JavaScript and ran in browsers.
Could be unrelated, but as I read this issue from top to bottom and it seemed to me there are some similitudes.

**Comment by Hywan** [comment] 2016-05-25 06:02
Messages are not partially received and I don't see any similitudes but you think so, let dive in. It does not change our priority regarding this issue. If you still experiment your issue after this one will be fixed, then we could restart trying to fix yours.

**Comment by Metalaka** [comment] 2016-05-25 20:23
Hi,
I post this update because I'll likely can't work on this for few weeks.

I have identified a use case which is related to this issue:

Actors:
- Server : S
- Client 1 : A
- Client 2 : B

```
- Start S
- Connect A to S
- handshake S - A
- Connect B to S
- handshake S - B

- S recieve a message from A
- S broadcast A's message to B
- B send a message ?
- B close the connection ?
- S recieve an empty message* from B
- S send a close message to B
- S can't send to B (because the connection is already closed by the client?), throw an error
- S recieve an empty message from A
- S close the connection to A (no error)
- …
```
So, I think it's when we send a message to a node before we had read the message that the node has sent that the errors are thrown. But, I don't even know if it comes from the server or client side.

*An empty message is considered as a normal close message by [Websocket/Protocol/Rfc6455#L121](https://github.com/hoaproject/Websocket/blob/5c91f2d73452a16320d3e5cc91e22c8a51b8baae/Protocol/Rfc6455.php#L121)

**Comment by Hywan** [comment] 2016-05-31 09:11
Thanks for the scenario! I will try to take the lead on this one so. When will you be able to come back?

**Comment by Hywan** [comment] 2016-07-05 20:13
@tomzx Can you retry with the latest release (https://github.com/hoaproject/Websocket/releases/tag/3.16.07.05) please? It possibly contains bug fixes or enhancement that could solve your issue.

Thanks!

**Comment by tomzx** [comment] 2016-07-05 23:20
I've try multiple times (25+ or so tests), and it seems the issue is still present. Furthermore, it appears that the amount of errors can sometimes go over the amount of connections that were established (503 errors vs 500 connections)

Here is my composer.lock, FYI [composer.lock.txt](https://github.com/hoaproject/Websocket/files/348809/composer.lock.txt)

**Comment by Hywan** [comment] 2016-07-06 06:45
Thank you very much :-). I was encoutering the issue mentionned by @Metalaka some days ago. The good news is this seems pretty easy to reproduce isolated. Hope to be back with a new patch soon.

**Comment by Shkarbatov** [comment] 2016-07-31 17:22
Hello, Hywan, what about patch? :)

**Comment by Hywan** [comment] 2016-08-04 05:51
Sorry, got some troubles. Will be able to work on it.

**Comment by Hywan** [comment] 2016-08-04 06:43
@tomzx Can you retry with the patches in https://github.com/hoaproject/Websocket/pull/71 please?

**Comment by tomzx** [comment] 2016-08-04 15:36
With the patch (updated the whole `Connection.php` file using 3.16.07.05 for all the other files)

```
error 36
[...]
connection 500
message 486
connection closed 500
```

It appears that the number of connection opened/closed at least matches now.

As for my earlier comment about 503 errors with 500 connections, it might be related to the fact that if all client connected at the same time and sent their message, there would be 500*500 possible broadcasted messages, or possible errors if they ended up disconnecting before they could receive the message. Thus it is sensible that more errors than connection can be generated IF we generate errors every time a message failed to be delivered.

**Comment by Hywan** [comment] 2016-08-08 07:15
@tomzx So, do you consider this is fixed?

**Comment by tomzx** [comment] 2016-08-08 10:42
The issue where connections where not all closed seems to be fixed.

However, if I have a single websocket client (started in a chrome console) and I run the same test where this websocket is never killed, I would expect it to receive 500 messages, but that is currently not the case.

Setup:
* Start the server in a terminal
* In a chrome console:
```
var ws = new WebSocket('ws://127.0.0.1:8889');
ws.onmessage = function(e) { console.log(e.data); }
```
* In the server terminal, you should see `connection 1`
* In a second terminal, run `ab -n 500 -c 5 -B 127.0.0.1 http://localhost/client.php`
* In this second terminal, observe
```
[...]
Complete requests:      500
Failed requests:        0
[...]
```
* In the server terminal, observe
```
connection 501
message 479
connection closed 500
```
* In the chrome console, observe
```
479 HELLO WORLD
```
* Note that this client should have received 500 messages as it was never killed. Furthermore, the server should have been able to properly send 500 messages to this client (is the loop sending the message to all clients exited if an error occurs while sending a message to a client?)

**Comment by Hywan** [comment] 2016-08-08 11:18
The server records 501 connections, which is correct. It also records 500 disconnections, which is correct too (500 from PHP client and 1 —still alive— browser client).

The server receives 479 messages, over 500 (sent from the PHP clients with `ab`).

The browser client receives 479 messages, so all the messages have been correctly broadcasted to it.

So yes, your issue that you expect to receive 500 messages, and not 479. Are you able to monitor the PHP clients to see if any errors are reported? This is not a broadcast error. The server reports 479 messages, and as far as I understand, each client only sent one message, so 1 client = 1 message. If the server receives only 479, it means that 21 clients have failed to connect or to send the message. This is why I would like to know if you have any errors from the PHP clients?

**Comment by tomzx** [comment] 2016-08-08 12:26
The apache server logs do not contain any errors regarding any uncaught exceptions or any other fatal error.

**Comment by Hywan** [comment] 2016-08-08 12:27
OK, I am going to investigate.

**Comment by Hywan** [comment] 2016-08-08 13:38
Here is my result.

From `ab -n 500 -c 100 127.0.0.1:80/Client.php`:
```
[…]
Concurrency Level:      100
Time taken for tests:   2.033 seconds
Complete requests:      500
Failed requests:        0
Total transferred:      81000 bytes
HTML transferred:       0 bytes
Requests per second:    245.90 [#/sec] (mean)
Time per request:       406.667 [ms] (mean)
Time per request:       4.067 [ms] (mean, across all concurrent requests)
Transfer rate:          38.90 [Kbytes/sec] received
[…]
```

From `php Server.php` (I print a summary for each connection, message, error or close):
```
connections: 500
messages:    500
errors:      2
closes:      500
```

From the browser:
![screen shot 2016-08-08 at 15 36 57](https://cloud.githubusercontent.com/assets/946104/17481531/fab65d24-5d7d-11e6-8ae8-c9793f46ed9d.png)
The message “Hello, World!” has been received 500 times.

So it seems like it is working.

I am using nginx + PHP-FPM + PHP7 (dev-master).

**Comment by Hywan** [comment] 2016-08-08 13:40
Without the PR #71, I have the following results.

From `php Server.php`:
```
connections: 501
messages:    500
errors:      97
closes:      418
```

From the browser:
```
500
```

**Comment by Hywan** [comment] 2016-08-08 13:41
Finally, if I call the `close` method in the client, I have 500 everywhere and 0 error.

From `php Server.php`:
```
connections: 501
messages:    500
errors:      0
closes:      500
```
From the browser:
```
500
```

**Comment by Hywan** [comment] 2016-08-08 13:44
And just because it's fun, here the result with 5000 connections and a concurrency level of 150.

From `ab -n 5000 -c 150 127.0.0.1:80/Client.php`:
```
Concurrency Level:      150
Time taken for tests:   32.075 seconds
Complete requests:      5000
Failed requests:        60
   (Connect: 0, Receive: 0, Length: 60, Exceptions: 0)
Non-2xx responses:      60
Total transferred:      819780 bytes
HTML transferred:       10380 bytes
Requests per second:    155.88 [#/sec] (mean)
Time per request:       962.265 [ms] (mean)
Time per request:       6.415 [ms] (mean, across all concurrent requests)
Transfer rate:          24.96 [Kbytes/sec] received
```
From `php Server.php`:
```
connections: 4940
messages:    4940
errors:      10
closes:      4940
```
From the browser:
```
4940
```

**The success rate is 98.8%** with a high concurrency (150 is not bad).

**Comment by Hywan** [comment] 2016-08-08 13:52
With a better PHP-FPM configuration, I drop from 32sec to 15sec to execute 5000 connections:

From `ab -n 5000 -c 150 127.0.0.1:80/Client.php`:
```
Concurrency Level:      150
Time taken for tests:   15.863 seconds
Complete requests:      5000
Failed requests:        13
   (Connect: 0, Receive: 0, Length: 13, Exceptions: 0)
Non-2xx responses:      13
Total transferred:      812119 bytes
HTML transferred:       2249 bytes
Requests per second:    315.21 [#/sec] (mean)
Time per request:       475.880 [ms] (mean)
Time per request:       3.173 [ms] (mean, across all concurrent requests)
Transfer rate:          50.00 [Kbytes/sec] received
```

**Comment by Hywan** [comment] 2017-03-24 14:20
#71 was the last PR related to this issue, and I guess all problems have been solved. If I am wrong, please, ping me and I will reopen this story.

Thanks for the report! It was very helpful to get better stability!

**Closed by Hywan** 2017-03-24 14:20 UTC
Labels: bug, difficulty: hard, in progress
